apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
   name: mysql-slave
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    name: http
    nodePort: 30067
  selector:
    name: mysql-slave