apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql-slave
spec:
  capacity:
    storage: 6Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /home/mysql_slave
    server: 192.168.115.6
  persistentVolumeReclaimPolicy: Recycle